[package]
name = 'Seam'
version = '0.2.2'

[addresses]


## protocol Integrations
pontem = '0x43417434fd869edee76cca2a4d2301e528a1551b1d719b75c350c3c97d15b8b9'
econia = '0xb1d4c0de8bc24468608637dfdbff975a0888f8935aa63338a44078eec5c7b6c7'

##


std = '0x1'
token = '0x3'
# Mock users for unit tests
user_1 = '0x3456'
user_2 = '0x4567'
user_3 = '0x5678'

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "main" }
