[package]
name = 'SeamDAO'
version = '0.2.2'

[addresses]
std = '0x1'
token = '0x3'
seamDao = "_"


## protocol Integrations
anime = '0x16fe2df00ea7dde4a63409201f7f4e536bde7bb7335526a35d05111e68aa322c'
liquid = '0x43417434fd869edee76cca2a4d2301e528a1551b1d719b75c350c3c97d15b8b9'


[dependencies]

Hippo = { local = "../deps/hippo-swap", addr_subst = { "Hippo" = "0xa61e1e86e9f596e483283727d2739ba24b919012720648c29380f9cd0a96c11a" }}

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "971c160079263a8d3e1d2503a570b01ecaaf10ba"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.hippo-swap]
local = "deps/hippo-swap"
